### ISSUE TITLE
Download not working

### ISSUE THREAD

**Issue by lehha** [AARInnovations/mibew-tray-notification-plugin#4]
How to download it?

http://www.any-file-backup.com/download.php?site=2&filename=TrayNotificationPlugin.zip

Server: nginx/1.8.0
Date: Wed, 12 Aug 2015 15:18:39 GMT
Content-Type: text/html; charset=UTF-8
Content-Length: 0
Connection: keep-alive

503 Service Unavailable

**Comment by AARInnovations** [comment]
Re: [mibew-tray-notification-plugin] Download not working (#4)

Hi,

It seems there was a temporary server downtime. As for now the file is acceptable at http://any-file-backup.com/TrayNotificationPlugin.zip 

Kind regards,

Support Group
E: support@any-file-backup.com | W: www.any-file-backup.com

AAR Innovations
E: support@aar-innovations.com | W: www.aar-innovations.com

Data replication, synchronization and monitoring solutions:
- AnyFileBackup PRO, LAN, FTP [ www.any-file-backup.com ]
- Ascella Log Monitor [ www.file-monitor.com/almplus/ascella-log-monitor-plus.html ]

Receive news by email: www.any-file-backup.com/rss/news_by_mail.php
RSS news feed: www.any-file-backup.com/rss/news.php

==============Original message text===============

> From: lehha notifications@github.com
> To: AARInnovations/mibew-tray-notification-plugin mibew-tray-notification-plugin@noreply.github.com
> Date: Wednesday, August 12, 2015, 6:19:10 PM
> Subject: [mibew-tray-notification-plugin] Download not working (#4)

How to download it?
http://www.any-file-backup.com/download.php?site=2&filename=TrayNotificationPlugin.zip
Server: nginx/1.8.0
Date: Wed, 12 Aug 2015 15:18:39 GMT
Content-Type: text/html; charset=UTF-8
Content-Length: 0
Connection: keep-alive
503 Service Unavailable

**Comment by lehha** [comment]
No. Still not working:

http://www.any-file-backup.com/download.php?site=2&filename=TrayNotificationPlugin.zip

Server: nginx/1.8.0
Date: Wed, 12 Aug 2015 20:22:33 GMT
Content-Type: text/html; charset=UTF-8
Content-Length: 0
Connection: keep-alive

503 Service Unavailable

**Comment by AARInnovations** [comment]
Re: [mibew-tray-notification-plugin] Download not working (#4)

Hi,

Looks like this might be a problem on some intermediate point. Try the downloading out with Tor browser.

Just in case the plugin is attached as well.

Kind regards,

Support Group
E: support@any-file-backup.com | W: www.any-file-backup.com

AAR Innovations
E: support@aar-innovations.com | W: www.aar-innovations.com

Data replication, synchronization and monitoring solutions:
- AnyFileBackup PRO, LAN, FTP [ www.any-file-backup.com ]
- Ascella Log Monitor [ www.file-monitor.com/almplus/ascella-log-monitor-plus.html ]

Receive news by email: www.any-file-backup.com/rss/news_by_mail.php
RSS news feed: www.any-file-backup.com/rss/news.php

==============Original message text===============

> From: lehha notifications@github.com
> To: AARInnovations/mibew-tray-notification-plugin mibew-tray-notification-plugin@noreply.github.com
> Date: Wednesday, August 12, 2015, 11:23:16 PM
> Subject: [mibew-tray-notification-plugin] Download not working (#4)

No. Still not working:
http://www.any-file-backup.com/download.php?site=2&filename=TrayNotificationPlugin.zip
Server: nginx/1.8.0
Date: Wed, 12 Aug 2015 20:22:33 GMT
Content-Type: text/html; charset=UTF-8
Content-Length: 0
Connection: keep-alive
503 Service Unavailable

**Comment by lehha** [comment]
Hmm, works in some time from other vpn. 

Look at the monitor from multiple locations, you have a problem with the availability:
http://ping-admin.ru/free_test/result/1439444079vrg1v5dr2i738f95go1v10.html

**Comment by AARInnovations** [comment]
Re: [mibew-tray-notification-plugin] Download not working (#4)

Hi,

Thank you for your investigation. We will research into it.

Kind regards,

Support Group
E: support@any-file-backup.com | W: www.any-file-backup.com

AAR Innovations
E: support@aar-innovations.com | W: www.aar-innovations.com

Data replication, synchronization and monitoring solutions:
- AnyFileBackup PRO, LAN, FTP [ www.any-file-backup.com ]
- Ascella Log Monitor [ www.file-monitor.com/almplus/ascella-log-monitor-plus.html ]

Receive news by email: www.any-file-backup.com/rss/news_by_mail.php
RSS news feed: www.any-file-backup.com/rss/news.php

==============Original message text===============

> From: lehha notifications@github.com
> To: AARInnovations/mibew-tray-notification-plugin mibew-tray-notification-plugin@noreply.github.com
> Date: Thursday, August 13, 2015, 8:38:48 AM
> Subject: [mibew-tray-notification-plugin] Download not working (#4)

Hmm, works in some time from other vpn. 
Look at the monitor from multiple locations, you have a problem with the availability:
http://ping-admin.ru/free_test/result/1439444079vrg1v5dr2i738f95go1v10.html

**Comment by hhhhwwww** [comment]
Plugin not working.

**Comment by AARInnovations** [comment]
Plugin successfully works with Mibew 3.1.2 and Chrome 66.
