### ISSUE TITLE
Doesn't work, Status: uninitialized

### ISSUE THREAD

**Issue by Netzvamp** [AARInnovations/mibew-tray-notification-plugin#5]
Hi, 
i've installed the plugin, activated it, but no Notifications are coming up. On the plugin-page the status of the plugin is "uninitialized". What can i do to get it working?

**Comment by AARInnovations** [comment]
Re: [mibew-tray-notification-plugin] Doesn't work, Status: uninitialized (#5)

Hi,

Thank you for your letter.

Please make sure the plugin's package was unzipped into the
"plugins" folder of the directory where mibew is installed. So the
directory chain should be "mibew/plugins/AARInnovations/Mibew/Plugin/TrayNotification".

Kind regards,

Support Group
E: support@any-file-backup.com | W: www.any-file-backup.com

AAR Innovations
E: support@aar-innovations.com | W: www.aar-innovations.com

Data replication, synchronization and monitoring solutions:
- AnyFileBackup PRO, LAN, FTP [ www.any-file-backup.com ]
- Ascella Log Monitor [ www.file-monitor.com/almplus/ascella-log-monitor-plus.html ]

Receive news by email: www.any-file-backup.com/rss/news_by_mail.php
RSS news feed: www.any-file-backup.com/rss/news.php

==============Original message text===============

> From: Netzvamp notifications@github.com
> To: AARInnovations/mibew-tray-notification-plugin mibew-tray-notification-plugin@noreply.github.com
> Date: Wednesday, January 13, 2016, 1:00:46 PM
> Subject: [mibew-tray-notification-plugin] Doesn't work, Status: uninitialized (#5)

Hi, 
i've installed the plugin, activated it, but no Notifications are coming up On the plugin-page the status of the plugin is "uninitialized" What can i do to get it working?

**Comment by Netzvamp** [comment]
Hello,
i'Ve installed mebew in a folder called "webchat", so path is "webchat/plugins/AARInnovations/Mibew/Plugin/TrayNotification". Is that the problem?

**Comment by AARInnovations** [comment]
Re: [mibew-tray-notification-plugin] Doesn't work, Status: uninitialized (#5)

Hello,

That should not be a problem if the Mibew plugin manager was able to find it and display in the available plugin list. Please check the plugin file and directory permissions. Actually we hadn't met the problem you reported.

Kind regards,

Support Group
E: support@any-file-backup.com | W: www.any-file-backup.com

AAR Innovations
E: support@aar-innovations.com | W: www.aar-innovations.com

Data replication, synchronization and monitoring solutions:
- AnyFileBackup PRO, LAN, FTP [ www.any-file-backup.com ]
- Ascella Log Monitor [ www.file-monitor.com/almplus/ascella-log-monitor-plus.html ]

Receive news by email: www.any-file-backup.com/rss/news_by_mail.php
RSS news feed: www.any-file-backup.com/rss/news.php

==============Original message text===============

> From: Netzvamp notifications@github.com
> To: AARInnovations/mibew-tray-notification-plugin mibew-tray-notification-plugin@noreply.github.com
> Date: Friday, January 15, 2016, 6:13:34 PM
> Subject: [mibew-tray-notification-plugin] Doesn't work, Status: uninitialized (#5)

Hello,
i'Ve installed mebew in a folder called "webchat", so path is "webchat/plugins/AARInnovations/Mibew/Plugin/TrayNotification". Is that the problem?

**Comment by davidherney** [comment]
Hi...

In order to activate the plugin, you need to put the plugin configuration in config/config.yml, as follows:

`plugins:`
   `"AARInnovations:TrayNotification":`
         `new_thread: true`

If you don't have another plugin, remember comment the next line:
`plugins: []`

Saludos

**Comment by hhhhwwww** [comment]
I have tested added configuration in config/config.yml as davidherney explained above and this shit doesn't work at all. The plugin is "uninitialized". The plugin state says: "not initialized".

**Comment by AARInnovations** [comment]
Plugin successfully works with Mibew 3.1.2 and Chrome 66.
