### ISSUE TITLE
plugin not working

### ISSUE THREAD

**Issue by solmaz90** [AARInnovations/mibew-tray-notification-plugin#6]
Hi every one
I have installed this plugin correctly but not working for me!
please help me how can i fix that?
Thanks in advanced
Solmaz

**Comment by AARInnovations** [comment]
Re: [AARInnovations/mibew-tray-notification-plugin] plugin not working (#6)


Hi,

Thank you for your message.

Did you try out a suggestion from the Mibew forum ?

Kind regards,
Support team

Thursday, August 31, 2017, 12:12:49 PM, you wrote:





Hi every one
I have installed this plugin correctly but not working for me!
please help me how can i fix that?
Thanks in advanced
Solmaz
—

**Comment by AARInnovations** [comment]
If you experience problems with the plugin in Chrome browser please note that the Notification API may no longer be used from insecure origins. You should consider switching to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details.
