### ISSUE TITLE
No notification

### ISSUE THREAD

**Issue by ang-e-lica** [AARInnovations/mibew-tray-notification-plugin#8]
Hi, I've installed and activated the plugin, everything seems ok and I've added the configuration in the mibew config file (as suggested in another issue) but no notification appears with Mibew 3.2.8 and Chrome 94. I also tried with Firefox but it still not working. What can I do?

Thanks in advance

**Comment by AARInnovations** [comment]
Unfortunately we stopped Mibew plugins support. So you can use them as a reference or example only. The plugin had been tested and used with Mibew version 2.XX. We didn't test it with the latest version of Mibew yet.

Best regards,
Support group
AAR Innovations
